# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-16 18:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStep', models.DateTimeField(verbose_name='Fecha')),
                ('points1', models.IntegerField(default=0, verbose_name='Puntos 1')),
                ('points2', models.IntegerField(default=0, verbose_name='Puntos 2')),
            ],
            options={
                'verbose_name': 'Combate',
            },
        ),
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=20, verbose_name='Alias')),
                ('strength', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Fuerza')),
                ('dexterity', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Destreza')),
                ('resistance', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Resistencia')),
            ],
            options={
                'verbose_name': 'Luchador',
                'verbose_name_plural': 'Luchadores',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Nombre')),
                ('create_date', models.DateField(verbose_name='Fecha de Creación')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('numberPlayers', models.IntegerField(default=0, verbose_name='Nº Jugadores')),
                ('type', models.IntegerField(choices=[(0, 'Fuerza'), (1, 'Destreza'), (2, 'Resistencia')], default=0, verbose_name='Tipo')),
                ('strengthWeigth', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Peso Fuerza')),
                ('dexterityWeigth', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Peso Destreza')),
                ('resistanceWeigth', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Peso Resistencia')),
                ('classified1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournamentClassified1', to='app.Fighter', verbose_name='1º clasificado')),
                ('classified2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournamentClassified2', to='app.Fighter', verbose_name='2º clasificado')),
                ('classified3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournamentClassified3', to='app.Fighter', verbose_name='3º clasificado')),
            ],
            options={
                'verbose_name': 'Torneo',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=30, verbose_name='Apellido')),
                ('country', models.CharField(max_length=50, verbose_name='País')),
            ],
            options={
                'verbose_name': 'Usuario',
            },
        ),
        migrations.AddField(
            model_name='fighter',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='Id Usuario'),
        ),
        migrations.AddField(
            model_name='combat',
            name='alias1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combatAlias1', to='app.Fighter', verbose_name='Luchador 1'),
        ),
        migrations.AddField(
            model_name='combat',
            name='alias2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combatAlias2', to='app.Fighter', verbose_name='Luchador 2'),
        ),
        migrations.AddField(
            model_name='combat',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tournament', verbose_name='Torneo'),
        ),
        migrations.AddField(
            model_name='combat',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combat_winner', to='app.Fighter', verbose_name='Ganador'),
        ),
    ]
