# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180516_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='classified3',
        ),
    ]
