# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_tournament_classified3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='numberPlayers',
        ),
        migrations.AddField(
            model_name='tournament',
            name='numberRounds',
            field=models.IntegerField(choices=[(0, '2'), (1, '4'), (2, '8'), (3, '16'), (4, '32')], default=2, verbose_name='Nº Rondas'),
        ),
    ]
