# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180523_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='fighters',
            field=models.ManyToManyField(to='app.Fighter', verbose_name='Luchadores'),
        ),
    ]
