# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tournament_fighters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='classified1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournamentClassified1', to='app.Fighter', verbose_name='1º clasificado'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='classified2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournamentClassified2', to='app.Fighter', verbose_name='2º clasificado'),
        ),
    ]
