# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180523_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='numberRounds',
            field=models.IntegerField(default=2, verbose_name='Nº Rondas'),
        ),
    ]
