# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 07:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180524_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='numberRounds',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)], verbose_name='Nº Rondas'),
        ),
    ]
